import {
    AppLayoutComponent,
    AppFooterComponent,
    AppSideBarComponent,
} from "./_layouts";

/**Components */
import {
    NotFoundComponent,
    AboutComponent,
    HomeComponent,
    CareerComponent,
    ChildComponent,
    ChildFilterComponent,
    LoginComponent,
    MobileAppsComponent,
    OrderComponent,
    TermComponent,
    MenuComponent,
    ContactUsComponent,
    VerifyComponent,
    GooglePlaceComponent,
    HomeAboutComponent,
    UserLeftMenuComponent,
    UserStartComponent,
    UserOrdersComponent,
    UserOrdersDetailComponent,
    UserAddressesComponent,
    UserFavouriteComponent,
    UserDetailsComponent,
    UserChangePassComponent,
    AddressCreationComponent,
    UserBannerComponent,
    AddressDetailsComponent,
    RestaurantSearchingComponent,
    MenuHeaderComponent,
    RestaurantMenuComponent,
    MenuItemsComponent,
    ShoppingBagsComponent,
    RestaurantReviewsComponent,
    OrderCheckoutDialogComponent,
    OrderCheckoutComponent,
    OrderConfirmComponent,
    RestaurantInfoComponent,
} from './components';

export const SharedComponents = [
    NotFoundComponent,
    AppLayoutComponent,
    AppFooterComponent,
    AppSideBarComponent,
    AboutComponent,
    HomeComponent,
    CareerComponent,
    ChildComponent,
    ChildFilterComponent,
    LoginComponent,
    MobileAppsComponent,
    OrderComponent,
    TermComponent,
    MenuComponent,
    ContactUsComponent,
    VerifyComponent,
    GooglePlaceComponent,
    HomeAboutComponent,
    UserLeftMenuComponent,
    UserStartComponent,
    UserOrdersComponent,
    UserOrdersDetailComponent,
    UserAddressesComponent,
    UserFavouriteComponent,
    UserDetailsComponent,
    UserChangePassComponent,
    AddressCreationComponent,
    UserBannerComponent,
    AddressDetailsComponent,
    RestaurantSearchingComponent,
    MenuHeaderComponent,
    RestaurantMenuComponent,
    MenuItemsComponent,
    ShoppingBagsComponent,
    RestaurantReviewsComponent,
    OrderCheckoutDialogComponent,
    OrderCheckoutComponent,
    OrderConfirmComponent,
    RestaurantInfoComponent,
];