import {
    AdminHeaderComponent,
    AdminLayoutComponent,
    AdminSideBarComponent
} from "../_layouts";

import {
    AdminCategoryComponent,
    AdminCategoryCreationComponent,
    AdminCategoryDetailComponent,
    AdminRestaurantComponent,
    AdminRestaurantCreationComponent,
    AdminRestaurantDetailComponent,
    AdminMenuComponent,
    AdminMenuCreationComponent,
    AdminMenuDetailComponent,
    AdminCommentComponent,
    AdminCommentCreationComponent,
    AdminCommentDetailComponent,
    AdminFavouriteComponent,
    AdminRoleComponent,
    AdminRoleCreationComponent,
    AdminRoleDetailComponent,
    AdminAddressComponent,
    AdminRatingComponent,
    AdminRatingCreationComponent,
    AdminRatingDetailComponent,
    AdminUserComponent,
    AdminUserCreationComponent,
    AdminUserDetailComponent,
    AdminMenuItemComponent,
    AdminMenuItemCreationComponent,
    AdminMenuItemDetailComponent,
    AdminPromotionComponent,
    AdminPromotionCreationComponent,
    AdminPromotionDetailComponent
} from './components';

export const AdminSharedComponents = [
    AdminHeaderComponent,
    AdminLayoutComponent,
    AdminSideBarComponent,
    AdminCategoryComponent,
    AdminCategoryCreationComponent,
    AdminCategoryDetailComponent,
    AdminRestaurantComponent,
    AdminRestaurantCreationComponent,
    AdminRestaurantDetailComponent,
    AdminMenuComponent,
    AdminMenuCreationComponent,
    AdminMenuDetailComponent,
    AdminCommentComponent,
    AdminCommentCreationComponent,
    AdminCommentDetailComponent,
    AdminFavouriteComponent,
    AdminRoleComponent,
    AdminRoleCreationComponent,
    AdminRoleDetailComponent,
    AdminAddressComponent,
    AdminRatingComponent,
    AdminRatingCreationComponent,
    AdminRatingDetailComponent,
    AdminUserComponent,
    AdminUserCreationComponent,
    AdminUserDetailComponent,
    AdminMenuItemComponent,
    AdminMenuItemCreationComponent,
    AdminMenuItemDetailComponent,
    AdminPromotionComponent,
    AdminPromotionCreationComponent,
    AdminPromotionDetailComponent
];