import {
    OwnerHeaderComponent,
    OwnerLayoutComponent,
    OwnerSideBarComponent
} from "../_layouts";

import {
    OwnerContactInfoComponent,
    OwnerInvoicingAddressComponent,
    OwnerContactsComponent,
    OwnerOrdersComponent,
    OwnerOrdersDetailComponent,
    OwnerRatingsComponent,
    OwnerCommentDetailComponent,
    OwnerArchiveComponent,
    OwnerMerchandiseInfoComponent,
    OwnerMerchandiseOrderStatusComponent,
    OwnerMerchandiseDeliveryBagsComponent,
    OwnerInvoicesComponent,
    OwnerInvoicesDetailComponent,
    OwnerPendingChargesComponent,
    OwnerPendingChargesDetailComponent,
    OwnerOnlinePaymentsComponent,
    OwnerMerchandiseBoxesComponent,
    OwnerMerchandiseJacketsComponent,
    OwnerAdvertisementInfoComponent,
    OwnerSoftwareComponent,
    OwnerMenuComponent,
    OwnerMenuCreationComponent,
    OwnerMenuDetailComponent,
    OwnerMenuItemComponent,
    OwnerMenuItemCreationComponent,
    OwnerMenuItemDetailComponent,
    OwnerPromotionComponent,
    OwnerPromotionCreationComponent,
    OwnerPromotionDetailComponent
} from './components';

export const OwnerSharedComponents = [
    OwnerHeaderComponent,
    OwnerLayoutComponent,
    OwnerSideBarComponent,
    OwnerContactInfoComponent,
    OwnerInvoicingAddressComponent,
    OwnerContactsComponent,
    OwnerOrdersComponent,
    OwnerOrdersDetailComponent,
    OwnerRatingsComponent,
    OwnerCommentDetailComponent,
    OwnerArchiveComponent,
    OwnerMerchandiseInfoComponent,
    OwnerMerchandiseOrderStatusComponent,
    OwnerMerchandiseDeliveryBagsComponent,
    OwnerInvoicesComponent,
    OwnerInvoicesDetailComponent,
    OwnerPendingChargesComponent,
    OwnerPendingChargesDetailComponent,
    OwnerOnlinePaymentsComponent,
    OwnerMerchandiseBoxesComponent,
    OwnerMerchandiseJacketsComponent,
    OwnerAdvertisementInfoComponent,
    OwnerSoftwareComponent,
    OwnerMenuComponent,
    OwnerMenuCreationComponent,
    OwnerMenuDetailComponent,
    OwnerMenuItemComponent,
    OwnerMenuItemCreationComponent,
    OwnerMenuItemDetailComponent,
    OwnerPromotionComponent,
    OwnerPromotionCreationComponent,
    OwnerPromotionDetailComponent
];